FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY database_exporter.py .

EXPOSE 9187

USER nobody

CMD ["python", "database_exporter.py"]