{
 "title": "New dashboard",
 "time": { "from": "2025-11-10T04:46:35.489Z", "to": "2025-11-10T07:55:15.490Z" },
 "templating": {
  "list": [
   {
    "name": "database",
    "label": "Database",
    "query": "postgres, template1, template0, dataVis, dataVis3, nest-db, online_store"
   }
  ]
 },
 "panels": [
  {
   "title": "Dead Tuples",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "pg_stat_user_tables_n_dead_tup{datname=~\"$database\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions Committed per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{datname=~\"$database\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_blks_hit{datname=~\"$database\"}[5m]) / (rate(pg_stat_database_blks_hit{datname=~\"$database\"}[5m]) + rate(pg_stat_database_blks_read{datname=~\"$database\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "pg_stat_database_numbackends{datname=~\"$database\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tuples Deleted per Second",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_deleted{datname=~\"$database\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction Rollbacks per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_rollback{datname=~\"$database\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tuples Inserted per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_inserted{datname=~\"$database\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tuples Updated per Second",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_updated{datname=~\"$database\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=~\"$database\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tuples Returned per Second",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_blks_hit{datname=~\"$database\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}